### ISSUE TITLE
program is not creating a table in menu.py

### ISSUE THREAD

**Issue by Hockeydan25** [Hockeydan25/Chainsaw_db#1]
@claraj could you help with me seeing why this won't create a table.

**Comment by claraj** [comment]
Are you missing the commit statement? https://github.com/Hockeydan25/Chainsaw_db/blob/3afeb7a3a6c6b187aa6e81596197443f6f241552/menu.py#L42

**Comment by Hockeydan25** [comment]
moved call to create db into main before menu launch to solve.

**Comment by Hockeydan25** [comment]
@claraj I did add that to line 42 and removed call from main that works. I had though the written with use of context manager and it took care of that like magic. Thank you for the hint.
